### ISSUE TITLE
Docker network over multi-host machine

### ISSUE THREAD

**Issue by forjin-vpac-innovations** [vpac-innovations/rsa#40]
Here are document I found.

https://github.com/docker/libnetwork/issues/757
: it means need to install(create AWS with ubuntu 15.04 at least).

Docker network
https://docs.docker.com/engine/userguide/networking/dockernetworks/

Docker network plugin
https://docs.docker.com/engine/extend/plugins_network/

**Comment by z0u** [comment]
I think we have these options:
1. Assume one Akka container per host, and use [host networking](https://docs.docker.com/engine/userguide/networking/dockernetworks/) `docker run --net=host [...]`. This means the container will share the same network interface as the host, and a broadcast message should work.
   
   Cons: limited networking options, not as secure
2. Use an _overlay_ network and Docker Swarm, somehow using [Swarm's service discovery](https://docs.docker.com/engine/userguide/networking/get-started-overlay/) instead of broadcast messages to find other nodes.
   
   Cons: more development in RSA, RSA might have to be aware of Docker
3. Use a network plugin like [Weave](http://docs.weave.works/weave/latest_release/plugin.html) that supports broadcast messages
   
   Cons: requires a 3rd-party plugin for Docker (risky?)
4. <del>Use Swarm and regular broadcast messages</del> [Not possible yet](https://github.com/docker/docker/issues/17814)

I would say that the first option is the worst in the long run, but probably the easiest to implement. The last is the best option but not possible yet.

**Comment by forjin-vpac-innovations** [comment]
Thanks, Alex.

I choose Number one option on AWS, it was successful until now.
So I think --net=host option is easy to set up a rsa instance. 

The other thins I need to do is setup a clustered storage such as AWS EFS, Gluster or Softness.
I think Gluster is better option but in large files Softnas is good for reading and writing according to [this document](http://www.metaltoad.com/blog/NFS-performance-AWS-EFS-SoftNAS-GlusterFS)

**Comment by z0u** [comment]
Cool, thanks Jin. If it works let's close this issue and create a new one for the file system.
